parameters:
  env(VARNISH_URL): ''

api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  title: Cms
  version: 0.18.1
  collection:
    pagination:
      page_parameter_name: _page
      items_per_page_parameter_name: _limit
      client_items_per_page: true
      items_per_page: 10
      maximum_items_per_page: 100
  http_cache:
    invalidation:
      enabled: false
    max_age: 0
    shared_max_age: 3600
    vary: ['Content-Type', 'Authorization']
    public: true

services:
  app.filter.data.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        slug: exact
    tags:
      - { name: api_platform.filter, id: app.data.search }

  app.filter.data.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.data.search_translation }

  app.filter.data.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.data.date }

  app.filter.data.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.data.order }

  app.filter.file.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        slug: exact
        type: exact
    tags:
      - { name: api_platform.filter, id: app.file.search }

  app.filter.file.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.file.search_translation }

  app.filter.file.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.file.date }

  app.filter.file.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.file.order }

  app.filter.text.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        slug: exact
    tags:
      - { name: api_platform.filter, id: app.text.search }

  app.filter.text.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.text.search_translation }

  app.filter.text.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.text.date }

  app.filter.text.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.text.order }

  app.filter.page.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        slug: exact
    tags:
      - { name: api_platform.filter, id: app.page.search }

  app.filter.page.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.page.search_translation }

  app.filter.page.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.page.date }

  app.filter.page.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.page.order }
