security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    system:
      pattern: ^/system
      stateless: true
      provider: ds_system
      http_basic: ~
    api:
      pattern: ^/
      stateless: true
      anonymous: true
      provider: ds_security
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/system,         role: ROLE_SYSTEM }
    - { path: ^/permissions,    role: IS_AUTHENTICATED_FULLY }
    - { path: ^/accesses,       role: IS_AUTHENTICATED_FULLY }
    - { path: ^/configs,        role: IS_AUTHENTICATED_FULLY }
    - { path: ^/datas,          role: IS_AUTHENTICATED_FULLY }
    - { path: ^/files,          role: IS_AUTHENTICATED_FULLY }
    - { path: ^/texts,          role: IS_AUTHENTICATED_FULLY }
    - { path: ^/content,        role: IS_AUTHENTICATED_ANONYMOUSLY }
