security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            anonymous: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/permissions,    role: IS_AUTHENTICATED_FULLY }
        - { path: ^/accesses,       role: IS_AUTHENTICATED_FULLY }
        - { path: ^/configs,        role: IS_AUTHENTICATED_FULLY }
        - { path: ^/content,        role: IS_AUTHENTICATED_ANONYMOUSLY }
