parameters:
    _data: Ds\Bundle\ContentBundle\Entity\Data
    _file: Ds\Bundle\ContentBundle\Entity\File
    _text: Ds\Bundle\ContentBundle\Entity\Text

ds_security:
    permissions:
        data:               { title: Data,        entity: '%_data%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        data_field:         { title: All Fields,  field:  '%_data%.*',            attributes: [BROWSE, READ, EDIT] }

        file:               { title: File,        entity: '%_file%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        file_field:         { title: All Fields,  field:  '%_file%.*',            attributes: [BROWSE, READ, EDIT] }

        text:               { title: Text,        entity: '%_text%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        text_field:         { title: All Fields,  field:  '%_text%.*',            attributes: [BROWSE, READ, EDIT] }
