services:
    ds_content.service.data:
        class: Ds\Bundle\ContentBundle\Service\DataService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\ContentBundle\Entity\Data

    ds_content.service.file:
        class: Ds\Bundle\ContentBundle\Service\FileService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\ContentBundle\Entity\File

    ds_content.service.text:
        class: Ds\Bundle\ContentBundle\Service\TextService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\ContentBundle\Entity\Text

    ds_content.filter.data.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { id: exact, uuid: exact, owner: exact, ownerUuid: exact }
        tags:
            - { name: api_platform.filter, id: ds.data.search }

    ds_content.filter.data.search_translation:
        parent: ds_translation.doctrine.orm.filter.search
        arguments:
            - { title: partial }
        tags:
            - { name: api_platform.filter, id: ds.data.search_translation }

    ds_content.filter.data.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            - { createdAt: ~, updatedAt: ~, deletedAt: ~ }
        tags:
            - { name: api_platform.filter, id: ds.data.date }

    ds_content.filter.data.order:
        parent: api_platform.doctrine.orm.order_filter
        arguments:
            - { id: ~, createdAt: ~, updatedAt: ~, deletedAt: ~, owner: ~ }
        tags:
            - { name: api_platform.filter, id: ds.data.order }

    ds_content.filter.file.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { id: exact, uuid: exact, owner: exact, ownerUuid: exact }
        tags:
            - { name: api_platform.filter, id: ds.file.search }

    ds_content.filter.file.search_translation:
        parent: ds_translation.doctrine.orm.filter.search
        arguments:
            - { title: partial }
        tags:
            - { name: api_platform.filter, id: ds.file.search_translation }

    ds_content.filter.file.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            - { createdAt: ~, updatedAt: ~, deletedAt: ~ }
        tags:
            - { name: api_platform.filter, id: ds.file.date }

    ds_content.filter.file.order:
        parent: api_platform.doctrine.orm.order_filter
        arguments:
            - { id: ~, createdAt: ~, updatedAt: ~, deletedAt: ~, owner: ~ }
        tags:
            - { name: api_platform.filter, id: ds.file.order }

    ds_content.filter.text.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { id: exact, uuid: exact, owner: exact, ownerUuid: exact }
        tags:
            - { name: api_platform.filter, id: ds.text.search }

    ds_content.filter.text.search_translation:
        parent: ds_translation.doctrine.orm.filter.search
        arguments:
            - { title: partial }
        tags:
            - { name: api_platform.filter, id: ds.text.search_translation }

    ds_content.filter.text.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            - { createdAt: ~, updatedAt: ~, deletedAt: ~ }
        tags:
            - { name: api_platform.filter, id: ds.text.date }

    ds_content.filter.text.order:
        parent: api_platform.doctrine.orm.order_filter
        arguments:
            - { id: ~, createdAt: ~, updatedAt: ~, deletedAt: ~, owner: ~ }
        tags:
            - { name: api_platform.filter, id: ds.text.order }
