services:
  app.tenant.loader.access:
    class: AppBundle\Tenant\Loader\AccessLoader
    arguments:
      - '@ds_security.service.access'
      - '@ds_security.service.permission'
    tags:
      - { name: ds_tenant.loader }

  app.tenant.loader.config:
    class: AppBundle\Tenant\Loader\ConfigLoader
    arguments:
      - '@ds_config.service.config'
    tags:
      - { name: ds_tenant.loader }

  app.tenant.unloader.data:
    class: AppBundle\Tenant\Unloader\DataUnloader
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader }

  app.tenant.unloader.file:
    class: AppBundle\Tenant\Unloader\FileUnloader
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader }

  app.tenant.unloader.page:
    class: AppBundle\Tenant\Unloader\PageUnloader
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader }

  app.tenant.unloader.text:
    class: AppBundle\Tenant\Unloader\TextUnloader
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader }
